[package]
name = "dfns_gen"
version = "0.1.0"
edition = "2021"
default-run = "convert"

[[bin]]
name = "convert"
path = "src/main.rs"

[[bin]]
name = "downgrade"
path = "src/downgrade.rs"

[dependencies]
oas3 = { version = "0.19.0", features = ["yaml-spec"] }
oas3-gen = "0.2.0"
oasert = "0.1.4"
openapi_type_picker = "0.2.4"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
